
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Ticket` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Ticket
 * 
 */
export type TicketModel = runtime.Types.Result.DefaultSelection<Prisma.$TicketPayload>

export type AggregateTicket = {
  _count: TicketCountAggregateOutputType | null
  _avg: TicketAvgAggregateOutputType | null
  _sum: TicketSumAggregateOutputType | null
  _min: TicketMinAggregateOutputType | null
  _max: TicketMaxAggregateOutputType | null
}

export type TicketAvgAggregateOutputType = {
  numero: number | null
  ordre: runtime.Decimal | null
  nb_reintegrations: number | null
}

export type TicketSumAggregateOutputType = {
  numero: number | null
  ordre: runtime.Decimal | null
  nb_reintegrations: number | null
}

export type TicketMinAggregateOutputType = {
  id: string | null
  cabinet_id: string | null
  date_file: Date | null
  numero: number | null
  type: $Enums.TicketType | null
  etat: $Enums.TicketEtat | null
  jeton_public: string | null
  nom_prive: string | null
  ordre: runtime.Decimal | null
  grace_expire_le: Date | null
  nb_reintegrations: number | null
  cree_le: Date | null
  appele_le: Date | null
  absent_le: Date | null
  debut_consult_le: Date | null
  fin_le: Date | null
}

export type TicketMaxAggregateOutputType = {
  id: string | null
  cabinet_id: string | null
  date_file: Date | null
  numero: number | null
  type: $Enums.TicketType | null
  etat: $Enums.TicketEtat | null
  jeton_public: string | null
  nom_prive: string | null
  ordre: runtime.Decimal | null
  grace_expire_le: Date | null
  nb_reintegrations: number | null
  cree_le: Date | null
  appele_le: Date | null
  absent_le: Date | null
  debut_consult_le: Date | null
  fin_le: Date | null
}

export type TicketCountAggregateOutputType = {
  id: number
  cabinet_id: number
  date_file: number
  numero: number
  type: number
  etat: number
  jeton_public: number
  nom_prive: number
  ordre: number
  grace_expire_le: number
  nb_reintegrations: number
  cree_le: number
  appele_le: number
  absent_le: number
  debut_consult_le: number
  fin_le: number
  _all: number
}


export type TicketAvgAggregateInputType = {
  numero?: true
  ordre?: true
  nb_reintegrations?: true
}

export type TicketSumAggregateInputType = {
  numero?: true
  ordre?: true
  nb_reintegrations?: true
}

export type TicketMinAggregateInputType = {
  id?: true
  cabinet_id?: true
  date_file?: true
  numero?: true
  type?: true
  etat?: true
  jeton_public?: true
  nom_prive?: true
  ordre?: true
  grace_expire_le?: true
  nb_reintegrations?: true
  cree_le?: true
  appele_le?: true
  absent_le?: true
  debut_consult_le?: true
  fin_le?: true
}

export type TicketMaxAggregateInputType = {
  id?: true
  cabinet_id?: true
  date_file?: true
  numero?: true
  type?: true
  etat?: true
  jeton_public?: true
  nom_prive?: true
  ordre?: true
  grace_expire_le?: true
  nb_reintegrations?: true
  cree_le?: true
  appele_le?: true
  absent_le?: true
  debut_consult_le?: true
  fin_le?: true
}

export type TicketCountAggregateInputType = {
  id?: true
  cabinet_id?: true
  date_file?: true
  numero?: true
  type?: true
  etat?: true
  jeton_public?: true
  nom_prive?: true
  ordre?: true
  grace_expire_le?: true
  nb_reintegrations?: true
  cree_le?: true
  appele_le?: true
  absent_le?: true
  debut_consult_le?: true
  fin_le?: true
  _all?: true
}

export type TicketAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Ticket to aggregate.
   */
  where?: Prisma.TicketWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tickets to fetch.
   */
  orderBy?: Prisma.TicketOrderByWithRelationInput | Prisma.TicketOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TicketWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tickets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tickets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Tickets
  **/
  _count?: true | TicketCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TicketAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TicketSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TicketMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TicketMaxAggregateInputType
}

export type GetTicketAggregateType<T extends TicketAggregateArgs> = {
      [P in keyof T & keyof AggregateTicket]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTicket[P]>
    : Prisma.GetScalarType<T[P], AggregateTicket[P]>
}




export type TicketGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TicketWhereInput
  orderBy?: Prisma.TicketOrderByWithAggregationInput | Prisma.TicketOrderByWithAggregationInput[]
  by: Prisma.TicketScalarFieldEnum[] | Prisma.TicketScalarFieldEnum
  having?: Prisma.TicketScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TicketCountAggregateInputType | true
  _avg?: TicketAvgAggregateInputType
  _sum?: TicketSumAggregateInputType
  _min?: TicketMinAggregateInputType
  _max?: TicketMaxAggregateInputType
}

export type TicketGroupByOutputType = {
  id: string
  cabinet_id: string
  date_file: Date
  numero: number
  type: $Enums.TicketType
  etat: $Enums.TicketEtat
  jeton_public: string
  nom_prive: string | null
  ordre: runtime.Decimal
  grace_expire_le: Date | null
  nb_reintegrations: number
  cree_le: Date
  appele_le: Date | null
  absent_le: Date | null
  debut_consult_le: Date | null
  fin_le: Date | null
  _count: TicketCountAggregateOutputType | null
  _avg: TicketAvgAggregateOutputType | null
  _sum: TicketSumAggregateOutputType | null
  _min: TicketMinAggregateOutputType | null
  _max: TicketMaxAggregateOutputType | null
}

export type GetTicketGroupByPayload<T extends TicketGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TicketGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TicketGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TicketGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TicketGroupByOutputType[P]>
      }
    >
  >



export type TicketWhereInput = {
  AND?: Prisma.TicketWhereInput | Prisma.TicketWhereInput[]
  OR?: Prisma.TicketWhereInput[]
  NOT?: Prisma.TicketWhereInput | Prisma.TicketWhereInput[]
  id?: Prisma.StringFilter<"Ticket"> | string
  cabinet_id?: Prisma.StringFilter<"Ticket"> | string
  date_file?: Prisma.DateTimeFilter<"Ticket"> | Date | string
  numero?: Prisma.IntFilter<"Ticket"> | number
  type?: Prisma.EnumTicketTypeFilter<"Ticket"> | $Enums.TicketType
  etat?: Prisma.EnumTicketEtatFilter<"Ticket"> | $Enums.TicketEtat
  jeton_public?: Prisma.StringFilter<"Ticket"> | string
  nom_prive?: Prisma.StringNullableFilter<"Ticket"> | string | null
  ordre?: Prisma.DecimalFilter<"Ticket"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  grace_expire_le?: Prisma.DateTimeNullableFilter<"Ticket"> | Date | string | null
  nb_reintegrations?: Prisma.IntFilter<"Ticket"> | number
  cree_le?: Prisma.DateTimeFilter<"Ticket"> | Date | string
  appele_le?: Prisma.DateTimeNullableFilter<"Ticket"> | Date | string | null
  absent_le?: Prisma.DateTimeNullableFilter<"Ticket"> | Date | string | null
  debut_consult_le?: Prisma.DateTimeNullableFilter<"Ticket"> | Date | string | null
  fin_le?: Prisma.DateTimeNullableFilter<"Ticket"> | Date | string | null
  cabinet?: Prisma.XOR<Prisma.CabinetScalarRelationFilter, Prisma.CabinetWhereInput>
}

export type TicketOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  cabinet_id?: Prisma.SortOrder
  date_file?: Prisma.SortOrder
  numero?: Prisma.SortOrder
  type?: Prisma.SortOrder
  etat?: Prisma.SortOrder
  jeton_public?: Prisma.SortOrder
  nom_prive?: Prisma.SortOrderInput | Prisma.SortOrder
  ordre?: Prisma.SortOrder
  grace_expire_le?: Prisma.SortOrderInput | Prisma.SortOrder
  nb_reintegrations?: Prisma.SortOrder
  cree_le?: Prisma.SortOrder
  appele_le?: Prisma.SortOrderInput | Prisma.SortOrder
  absent_le?: Prisma.SortOrderInput | Prisma.SortOrder
  debut_consult_le?: Prisma.SortOrderInput | Prisma.SortOrder
  fin_le?: Prisma.SortOrderInput | Prisma.SortOrder
  cabinet?: Prisma.CabinetOrderByWithRelationInput
}

export type TicketWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  jeton_public?: string
  cabinet_id_date_file_numero?: Prisma.TicketCabinet_idDate_fileNumeroCompoundUniqueInput
  AND?: Prisma.TicketWhereInput | Prisma.TicketWhereInput[]
  OR?: Prisma.TicketWhereInput[]
  NOT?: Prisma.TicketWhereInput | Prisma.TicketWhereInput[]
  cabinet_id?: Prisma.StringFilter<"Ticket"> | string
  date_file?: Prisma.DateTimeFilter<"Ticket"> | Date | string
  numero?: Prisma.IntFilter<"Ticket"> | number
  type?: Prisma.EnumTicketTypeFilter<"Ticket"> | $Enums.TicketType
  etat?: Prisma.EnumTicketEtatFilter<"Ticket"> | $Enums.TicketEtat
  nom_prive?: Prisma.StringNullableFilter<"Ticket"> | string | null
  ordre?: Prisma.DecimalFilter<"Ticket"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  grace_expire_le?: Prisma.DateTimeNullableFilter<"Ticket"> | Date | string | null
  nb_reintegrations?: Prisma.IntFilter<"Ticket"> | number
  cree_le?: Prisma.DateTimeFilter<"Ticket"> | Date | string
  appele_le?: Prisma.DateTimeNullableFilter<"Ticket"> | Date | string | null
  absent_le?: Prisma.DateTimeNullableFilter<"Ticket"> | Date | string | null
  debut_consult_le?: Prisma.DateTimeNullableFilter<"Ticket"> | Date | string | null
  fin_le?: Prisma.DateTimeNullableFilter<"Ticket"> | Date | string | null
  cabinet?: Prisma.XOR<Prisma.CabinetScalarRelationFilter, Prisma.CabinetWhereInput>
}, "id" | "jeton_public" | "cabinet_id_date_file_numero">

export type TicketOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  cabinet_id?: Prisma.SortOrder
  date_file?: Prisma.SortOrder
  numero?: Prisma.SortOrder
  type?: Prisma.SortOrder
  etat?: Prisma.SortOrder
  jeton_public?: Prisma.SortOrder
  nom_prive?: Prisma.SortOrderInput | Prisma.SortOrder
  ordre?: Prisma.SortOrder
  grace_expire_le?: Prisma.SortOrderInput | Prisma.SortOrder
  nb_reintegrations?: Prisma.SortOrder
  cree_le?: Prisma.SortOrder
  appele_le?: Prisma.SortOrderInput | Prisma.SortOrder
  absent_le?: Prisma.SortOrderInput | Prisma.SortOrder
  debut_consult_le?: Prisma.SortOrderInput | Prisma.SortOrder
  fin_le?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.TicketCountOrderByAggregateInput
  _avg?: Prisma.TicketAvgOrderByAggregateInput
  _max?: Prisma.TicketMaxOrderByAggregateInput
  _min?: Prisma.TicketMinOrderByAggregateInput
  _sum?: Prisma.TicketSumOrderByAggregateInput
}

export type TicketScalarWhereWithAggregatesInput = {
  AND?: Prisma.TicketScalarWhereWithAggregatesInput | Prisma.TicketScalarWhereWithAggregatesInput[]
  OR?: Prisma.TicketScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TicketScalarWhereWithAggregatesInput | Prisma.TicketScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Ticket"> | string
  cabinet_id?: Prisma.StringWithAggregatesFilter<"Ticket"> | string
  date_file?: Prisma.DateTimeWithAggregatesFilter<"Ticket"> | Date | string
  numero?: Prisma.IntWithAggregatesFilter<"Ticket"> | number
  type?: Prisma.EnumTicketTypeWithAggregatesFilter<"Ticket"> | $Enums.TicketType
  etat?: Prisma.EnumTicketEtatWithAggregatesFilter<"Ticket"> | $Enums.TicketEtat
  jeton_public?: Prisma.StringWithAggregatesFilter<"Ticket"> | string
  nom_prive?: Prisma.StringNullableWithAggregatesFilter<"Ticket"> | string | null
  ordre?: Prisma.DecimalWithAggregatesFilter<"Ticket"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  grace_expire_le?: Prisma.DateTimeNullableWithAggregatesFilter<"Ticket"> | Date | string | null
  nb_reintegrations?: Prisma.IntWithAggregatesFilter<"Ticket"> | number
  cree_le?: Prisma.DateTimeWithAggregatesFilter<"Ticket"> | Date | string
  appele_le?: Prisma.DateTimeNullableWithAggregatesFilter<"Ticket"> | Date | string | null
  absent_le?: Prisma.DateTimeNullableWithAggregatesFilter<"Ticket"> | Date | string | null
  debut_consult_le?: Prisma.DateTimeNullableWithAggregatesFilter<"Ticket"> | Date | string | null
  fin_le?: Prisma.DateTimeNullableWithAggregatesFilter<"Ticket"> | Date | string | null
}

export type TicketCreateInput = {
  id?: string
  date_file: Date | string
  numero: number
  type?: $Enums.TicketType
  etat?: $Enums.TicketEtat
  jeton_public: string
  nom_prive?: string | null
  ordre: runtime.Decimal | runtime.DecimalJsLike | number | string
  grace_expire_le?: Date | string | null
  nb_reintegrations?: number
  cree_le?: Date | string
  appele_le?: Date | string | null
  absent_le?: Date | string | null
  debut_consult_le?: Date | string | null
  fin_le?: Date | string | null
  cabinet: Prisma.CabinetCreateNestedOneWithoutTicketsInput
}

export type TicketUncheckedCreateInput = {
  id?: string
  cabinet_id: string
  date_file: Date | string
  numero: number
  type?: $Enums.TicketType
  etat?: $Enums.TicketEtat
  jeton_public: string
  nom_prive?: string | null
  ordre: runtime.Decimal | runtime.DecimalJsLike | number | string
  grace_expire_le?: Date | string | null
  nb_reintegrations?: number
  cree_le?: Date | string
  appele_le?: Date | string | null
  absent_le?: Date | string | null
  debut_consult_le?: Date | string | null
  fin_le?: Date | string | null
}

export type TicketUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date_file?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  numero?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumTicketTypeFieldUpdateOperationsInput | $Enums.TicketType
  etat?: Prisma.EnumTicketEtatFieldUpdateOperationsInput | $Enums.TicketEtat
  jeton_public?: Prisma.StringFieldUpdateOperationsInput | string
  nom_prive?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ordre?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  grace_expire_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  nb_reintegrations?: Prisma.IntFieldUpdateOperationsInput | number
  cree_le?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appele_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  absent_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  debut_consult_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fin_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  cabinet?: Prisma.CabinetUpdateOneRequiredWithoutTicketsNestedInput
}

export type TicketUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  cabinet_id?: Prisma.StringFieldUpdateOperationsInput | string
  date_file?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  numero?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumTicketTypeFieldUpdateOperationsInput | $Enums.TicketType
  etat?: Prisma.EnumTicketEtatFieldUpdateOperationsInput | $Enums.TicketEtat
  jeton_public?: Prisma.StringFieldUpdateOperationsInput | string
  nom_prive?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ordre?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  grace_expire_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  nb_reintegrations?: Prisma.IntFieldUpdateOperationsInput | number
  cree_le?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appele_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  absent_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  debut_consult_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fin_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TicketCreateManyInput = {
  id?: string
  cabinet_id: string
  date_file: Date | string
  numero: number
  type?: $Enums.TicketType
  etat?: $Enums.TicketEtat
  jeton_public: string
  nom_prive?: string | null
  ordre: runtime.Decimal | runtime.DecimalJsLike | number | string
  grace_expire_le?: Date | string | null
  nb_reintegrations?: number
  cree_le?: Date | string
  appele_le?: Date | string | null
  absent_le?: Date | string | null
  debut_consult_le?: Date | string | null
  fin_le?: Date | string | null
}

export type TicketUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date_file?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  numero?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumTicketTypeFieldUpdateOperationsInput | $Enums.TicketType
  etat?: Prisma.EnumTicketEtatFieldUpdateOperationsInput | $Enums.TicketEtat
  jeton_public?: Prisma.StringFieldUpdateOperationsInput | string
  nom_prive?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ordre?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  grace_expire_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  nb_reintegrations?: Prisma.IntFieldUpdateOperationsInput | number
  cree_le?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appele_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  absent_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  debut_consult_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fin_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TicketUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  cabinet_id?: Prisma.StringFieldUpdateOperationsInput | string
  date_file?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  numero?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumTicketTypeFieldUpdateOperationsInput | $Enums.TicketType
  etat?: Prisma.EnumTicketEtatFieldUpdateOperationsInput | $Enums.TicketEtat
  jeton_public?: Prisma.StringFieldUpdateOperationsInput | string
  nom_prive?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ordre?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  grace_expire_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  nb_reintegrations?: Prisma.IntFieldUpdateOperationsInput | number
  cree_le?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appele_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  absent_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  debut_consult_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fin_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TicketListRelationFilter = {
  every?: Prisma.TicketWhereInput
  some?: Prisma.TicketWhereInput
  none?: Prisma.TicketWhereInput
}

export type TicketOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TicketCabinet_idDate_fileNumeroCompoundUniqueInput = {
  cabinet_id: string
  date_file: Date | string
  numero: number
}

export type TicketCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cabinet_id?: Prisma.SortOrder
  date_file?: Prisma.SortOrder
  numero?: Prisma.SortOrder
  type?: Prisma.SortOrder
  etat?: Prisma.SortOrder
  jeton_public?: Prisma.SortOrder
  nom_prive?: Prisma.SortOrder
  ordre?: Prisma.SortOrder
  grace_expire_le?: Prisma.SortOrder
  nb_reintegrations?: Prisma.SortOrder
  cree_le?: Prisma.SortOrder
  appele_le?: Prisma.SortOrder
  absent_le?: Prisma.SortOrder
  debut_consult_le?: Prisma.SortOrder
  fin_le?: Prisma.SortOrder
}

export type TicketAvgOrderByAggregateInput = {
  numero?: Prisma.SortOrder
  ordre?: Prisma.SortOrder
  nb_reintegrations?: Prisma.SortOrder
}

export type TicketMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cabinet_id?: Prisma.SortOrder
  date_file?: Prisma.SortOrder
  numero?: Prisma.SortOrder
  type?: Prisma.SortOrder
  etat?: Prisma.SortOrder
  jeton_public?: Prisma.SortOrder
  nom_prive?: Prisma.SortOrder
  ordre?: Prisma.SortOrder
  grace_expire_le?: Prisma.SortOrder
  nb_reintegrations?: Prisma.SortOrder
  cree_le?: Prisma.SortOrder
  appele_le?: Prisma.SortOrder
  absent_le?: Prisma.SortOrder
  debut_consult_le?: Prisma.SortOrder
  fin_le?: Prisma.SortOrder
}

export type TicketMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cabinet_id?: Prisma.SortOrder
  date_file?: Prisma.SortOrder
  numero?: Prisma.SortOrder
  type?: Prisma.SortOrder
  etat?: Prisma.SortOrder
  jeton_public?: Prisma.SortOrder
  nom_prive?: Prisma.SortOrder
  ordre?: Prisma.SortOrder
  grace_expire_le?: Prisma.SortOrder
  nb_reintegrations?: Prisma.SortOrder
  cree_le?: Prisma.SortOrder
  appele_le?: Prisma.SortOrder
  absent_le?: Prisma.SortOrder
  debut_consult_le?: Prisma.SortOrder
  fin_le?: Prisma.SortOrder
}

export type TicketSumOrderByAggregateInput = {
  numero?: Prisma.SortOrder
  ordre?: Prisma.SortOrder
  nb_reintegrations?: Prisma.SortOrder
}

export type TicketCreateNestedManyWithoutCabinetInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutCabinetInput, Prisma.TicketUncheckedCreateWithoutCabinetInput> | Prisma.TicketCreateWithoutCabinetInput[] | Prisma.TicketUncheckedCreateWithoutCabinetInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutCabinetInput | Prisma.TicketCreateOrConnectWithoutCabinetInput[]
  createMany?: Prisma.TicketCreateManyCabinetInputEnvelope
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
}

export type TicketUncheckedCreateNestedManyWithoutCabinetInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutCabinetInput, Prisma.TicketUncheckedCreateWithoutCabinetInput> | Prisma.TicketCreateWithoutCabinetInput[] | Prisma.TicketUncheckedCreateWithoutCabinetInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutCabinetInput | Prisma.TicketCreateOrConnectWithoutCabinetInput[]
  createMany?: Prisma.TicketCreateManyCabinetInputEnvelope
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
}

export type TicketUpdateManyWithoutCabinetNestedInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutCabinetInput, Prisma.TicketUncheckedCreateWithoutCabinetInput> | Prisma.TicketCreateWithoutCabinetInput[] | Prisma.TicketUncheckedCreateWithoutCabinetInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutCabinetInput | Prisma.TicketCreateOrConnectWithoutCabinetInput[]
  upsert?: Prisma.TicketUpsertWithWhereUniqueWithoutCabinetInput | Prisma.TicketUpsertWithWhereUniqueWithoutCabinetInput[]
  createMany?: Prisma.TicketCreateManyCabinetInputEnvelope
  set?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  disconnect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  delete?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  update?: Prisma.TicketUpdateWithWhereUniqueWithoutCabinetInput | Prisma.TicketUpdateWithWhereUniqueWithoutCabinetInput[]
  updateMany?: Prisma.TicketUpdateManyWithWhereWithoutCabinetInput | Prisma.TicketUpdateManyWithWhereWithoutCabinetInput[]
  deleteMany?: Prisma.TicketScalarWhereInput | Prisma.TicketScalarWhereInput[]
}

export type TicketUncheckedUpdateManyWithoutCabinetNestedInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutCabinetInput, Prisma.TicketUncheckedCreateWithoutCabinetInput> | Prisma.TicketCreateWithoutCabinetInput[] | Prisma.TicketUncheckedCreateWithoutCabinetInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutCabinetInput | Prisma.TicketCreateOrConnectWithoutCabinetInput[]
  upsert?: Prisma.TicketUpsertWithWhereUniqueWithoutCabinetInput | Prisma.TicketUpsertWithWhereUniqueWithoutCabinetInput[]
  createMany?: Prisma.TicketCreateManyCabinetInputEnvelope
  set?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  disconnect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  delete?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  update?: Prisma.TicketUpdateWithWhereUniqueWithoutCabinetInput | Prisma.TicketUpdateWithWhereUniqueWithoutCabinetInput[]
  updateMany?: Prisma.TicketUpdateManyWithWhereWithoutCabinetInput | Prisma.TicketUpdateManyWithWhereWithoutCabinetInput[]
  deleteMany?: Prisma.TicketScalarWhereInput | Prisma.TicketScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type EnumTicketTypeFieldUpdateOperationsInput = {
  set?: $Enums.TicketType
}

export type EnumTicketEtatFieldUpdateOperationsInput = {
  set?: $Enums.TicketEtat
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type TicketCreateWithoutCabinetInput = {
  id?: string
  date_file: Date | string
  numero: number
  type?: $Enums.TicketType
  etat?: $Enums.TicketEtat
  jeton_public: string
  nom_prive?: string | null
  ordre: runtime.Decimal | runtime.DecimalJsLike | number | string
  grace_expire_le?: Date | string | null
  nb_reintegrations?: number
  cree_le?: Date | string
  appele_le?: Date | string | null
  absent_le?: Date | string | null
  debut_consult_le?: Date | string | null
  fin_le?: Date | string | null
}

export type TicketUncheckedCreateWithoutCabinetInput = {
  id?: string
  date_file: Date | string
  numero: number
  type?: $Enums.TicketType
  etat?: $Enums.TicketEtat
  jeton_public: string
  nom_prive?: string | null
  ordre: runtime.Decimal | runtime.DecimalJsLike | number | string
  grace_expire_le?: Date | string | null
  nb_reintegrations?: number
  cree_le?: Date | string
  appele_le?: Date | string | null
  absent_le?: Date | string | null
  debut_consult_le?: Date | string | null
  fin_le?: Date | string | null
}

export type TicketCreateOrConnectWithoutCabinetInput = {
  where: Prisma.TicketWhereUniqueInput
  create: Prisma.XOR<Prisma.TicketCreateWithoutCabinetInput, Prisma.TicketUncheckedCreateWithoutCabinetInput>
}

export type TicketCreateManyCabinetInputEnvelope = {
  data: Prisma.TicketCreateManyCabinetInput | Prisma.TicketCreateManyCabinetInput[]
  skipDuplicates?: boolean
}

export type TicketUpsertWithWhereUniqueWithoutCabinetInput = {
  where: Prisma.TicketWhereUniqueInput
  update: Prisma.XOR<Prisma.TicketUpdateWithoutCabinetInput, Prisma.TicketUncheckedUpdateWithoutCabinetInput>
  create: Prisma.XOR<Prisma.TicketCreateWithoutCabinetInput, Prisma.TicketUncheckedCreateWithoutCabinetInput>
}

export type TicketUpdateWithWhereUniqueWithoutCabinetInput = {
  where: Prisma.TicketWhereUniqueInput
  data: Prisma.XOR<Prisma.TicketUpdateWithoutCabinetInput, Prisma.TicketUncheckedUpdateWithoutCabinetInput>
}

export type TicketUpdateManyWithWhereWithoutCabinetInput = {
  where: Prisma.TicketScalarWhereInput
  data: Prisma.XOR<Prisma.TicketUpdateManyMutationInput, Prisma.TicketUncheckedUpdateManyWithoutCabinetInput>
}

export type TicketScalarWhereInput = {
  AND?: Prisma.TicketScalarWhereInput | Prisma.TicketScalarWhereInput[]
  OR?: Prisma.TicketScalarWhereInput[]
  NOT?: Prisma.TicketScalarWhereInput | Prisma.TicketScalarWhereInput[]
  id?: Prisma.StringFilter<"Ticket"> | string
  cabinet_id?: Prisma.StringFilter<"Ticket"> | string
  date_file?: Prisma.DateTimeFilter<"Ticket"> | Date | string
  numero?: Prisma.IntFilter<"Ticket"> | number
  type?: Prisma.EnumTicketTypeFilter<"Ticket"> | $Enums.TicketType
  etat?: Prisma.EnumTicketEtatFilter<"Ticket"> | $Enums.TicketEtat
  jeton_public?: Prisma.StringFilter<"Ticket"> | string
  nom_prive?: Prisma.StringNullableFilter<"Ticket"> | string | null
  ordre?: Prisma.DecimalFilter<"Ticket"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  grace_expire_le?: Prisma.DateTimeNullableFilter<"Ticket"> | Date | string | null
  nb_reintegrations?: Prisma.IntFilter<"Ticket"> | number
  cree_le?: Prisma.DateTimeFilter<"Ticket"> | Date | string
  appele_le?: Prisma.DateTimeNullableFilter<"Ticket"> | Date | string | null
  absent_le?: Prisma.DateTimeNullableFilter<"Ticket"> | Date | string | null
  debut_consult_le?: Prisma.DateTimeNullableFilter<"Ticket"> | Date | string | null
  fin_le?: Prisma.DateTimeNullableFilter<"Ticket"> | Date | string | null
}

export type TicketCreateManyCabinetInput = {
  id?: string
  date_file: Date | string
  numero: number
  type?: $Enums.TicketType
  etat?: $Enums.TicketEtat
  jeton_public: string
  nom_prive?: string | null
  ordre: runtime.Decimal | runtime.DecimalJsLike | number | string
  grace_expire_le?: Date | string | null
  nb_reintegrations?: number
  cree_le?: Date | string
  appele_le?: Date | string | null
  absent_le?: Date | string | null
  debut_consult_le?: Date | string | null
  fin_le?: Date | string | null
}

export type TicketUpdateWithoutCabinetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date_file?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  numero?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumTicketTypeFieldUpdateOperationsInput | $Enums.TicketType
  etat?: Prisma.EnumTicketEtatFieldUpdateOperationsInput | $Enums.TicketEtat
  jeton_public?: Prisma.StringFieldUpdateOperationsInput | string
  nom_prive?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ordre?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  grace_expire_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  nb_reintegrations?: Prisma.IntFieldUpdateOperationsInput | number
  cree_le?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appele_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  absent_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  debut_consult_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fin_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TicketUncheckedUpdateWithoutCabinetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date_file?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  numero?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumTicketTypeFieldUpdateOperationsInput | $Enums.TicketType
  etat?: Prisma.EnumTicketEtatFieldUpdateOperationsInput | $Enums.TicketEtat
  jeton_public?: Prisma.StringFieldUpdateOperationsInput | string
  nom_prive?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ordre?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  grace_expire_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  nb_reintegrations?: Prisma.IntFieldUpdateOperationsInput | number
  cree_le?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appele_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  absent_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  debut_consult_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fin_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type TicketUncheckedUpdateManyWithoutCabinetInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date_file?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  numero?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumTicketTypeFieldUpdateOperationsInput | $Enums.TicketType
  etat?: Prisma.EnumTicketEtatFieldUpdateOperationsInput | $Enums.TicketEtat
  jeton_public?: Prisma.StringFieldUpdateOperationsInput | string
  nom_prive?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ordre?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  grace_expire_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  nb_reintegrations?: Prisma.IntFieldUpdateOperationsInput | number
  cree_le?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appele_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  absent_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  debut_consult_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  fin_le?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type TicketSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  cabinet_id?: boolean
  date_file?: boolean
  numero?: boolean
  type?: boolean
  etat?: boolean
  jeton_public?: boolean
  nom_prive?: boolean
  ordre?: boolean
  grace_expire_le?: boolean
  nb_reintegrations?: boolean
  cree_le?: boolean
  appele_le?: boolean
  absent_le?: boolean
  debut_consult_le?: boolean
  fin_le?: boolean
  cabinet?: boolean | Prisma.CabinetDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ticket"]>

export type TicketSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  cabinet_id?: boolean
  date_file?: boolean
  numero?: boolean
  type?: boolean
  etat?: boolean
  jeton_public?: boolean
  nom_prive?: boolean
  ordre?: boolean
  grace_expire_le?: boolean
  nb_reintegrations?: boolean
  cree_le?: boolean
  appele_le?: boolean
  absent_le?: boolean
  debut_consult_le?: boolean
  fin_le?: boolean
  cabinet?: boolean | Prisma.CabinetDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ticket"]>

export type TicketSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  cabinet_id?: boolean
  date_file?: boolean
  numero?: boolean
  type?: boolean
  etat?: boolean
  jeton_public?: boolean
  nom_prive?: boolean
  ordre?: boolean
  grace_expire_le?: boolean
  nb_reintegrations?: boolean
  cree_le?: boolean
  appele_le?: boolean
  absent_le?: boolean
  debut_consult_le?: boolean
  fin_le?: boolean
  cabinet?: boolean | Prisma.CabinetDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ticket"]>

export type TicketSelectScalar = {
  id?: boolean
  cabinet_id?: boolean
  date_file?: boolean
  numero?: boolean
  type?: boolean
  etat?: boolean
  jeton_public?: boolean
  nom_prive?: boolean
  ordre?: boolean
  grace_expire_le?: boolean
  nb_reintegrations?: boolean
  cree_le?: boolean
  appele_le?: boolean
  absent_le?: boolean
  debut_consult_le?: boolean
  fin_le?: boolean
}

export type TicketOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "cabinet_id" | "date_file" | "numero" | "type" | "etat" | "jeton_public" | "nom_prive" | "ordre" | "grace_expire_le" | "nb_reintegrations" | "cree_le" | "appele_le" | "absent_le" | "debut_consult_le" | "fin_le", ExtArgs["result"]["ticket"]>
export type TicketInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cabinet?: boolean | Prisma.CabinetDefaultArgs<ExtArgs>
}
export type TicketIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cabinet?: boolean | Prisma.CabinetDefaultArgs<ExtArgs>
}
export type TicketIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cabinet?: boolean | Prisma.CabinetDefaultArgs<ExtArgs>
}

export type $TicketPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Ticket"
  objects: {
    cabinet: Prisma.$CabinetPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    cabinet_id: string
    date_file: Date
    numero: number
    type: $Enums.TicketType
    etat: $Enums.TicketEtat
    jeton_public: string
    nom_prive: string | null
    ordre: runtime.Decimal
    grace_expire_le: Date | null
    nb_reintegrations: number
    cree_le: Date
    appele_le: Date | null
    absent_le: Date | null
    debut_consult_le: Date | null
    fin_le: Date | null
  }, ExtArgs["result"]["ticket"]>
  composites: {}
}

export type TicketGetPayload<S extends boolean | null | undefined | TicketDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TicketPayload, S>

export type TicketCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TicketFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TicketCountAggregateInputType | true
  }

export interface TicketDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Ticket'], meta: { name: 'Ticket' } }
  /**
   * Find zero or one Ticket that matches the filter.
   * @param {TicketFindUniqueArgs} args - Arguments to find a Ticket
   * @example
   * // Get one Ticket
   * const ticket = await prisma.ticket.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TicketFindUniqueArgs>(args: Prisma.SelectSubset<T, TicketFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Ticket that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TicketFindUniqueOrThrowArgs} args - Arguments to find a Ticket
   * @example
   * // Get one Ticket
   * const ticket = await prisma.ticket.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TicketFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TicketFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Ticket that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketFindFirstArgs} args - Arguments to find a Ticket
   * @example
   * // Get one Ticket
   * const ticket = await prisma.ticket.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TicketFindFirstArgs>(args?: Prisma.SelectSubset<T, TicketFindFirstArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Ticket that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketFindFirstOrThrowArgs} args - Arguments to find a Ticket
   * @example
   * // Get one Ticket
   * const ticket = await prisma.ticket.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TicketFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TicketFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tickets that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tickets
   * const tickets = await prisma.ticket.findMany()
   * 
   * // Get first 10 Tickets
   * const tickets = await prisma.ticket.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const ticketWithIdOnly = await prisma.ticket.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TicketFindManyArgs>(args?: Prisma.SelectSubset<T, TicketFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Ticket.
   * @param {TicketCreateArgs} args - Arguments to create a Ticket.
   * @example
   * // Create one Ticket
   * const Ticket = await prisma.ticket.create({
   *   data: {
   *     // ... data to create a Ticket
   *   }
   * })
   * 
   */
  create<T extends TicketCreateArgs>(args: Prisma.SelectSubset<T, TicketCreateArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tickets.
   * @param {TicketCreateManyArgs} args - Arguments to create many Tickets.
   * @example
   * // Create many Tickets
   * const ticket = await prisma.ticket.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TicketCreateManyArgs>(args?: Prisma.SelectSubset<T, TicketCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tickets and returns the data saved in the database.
   * @param {TicketCreateManyAndReturnArgs} args - Arguments to create many Tickets.
   * @example
   * // Create many Tickets
   * const ticket = await prisma.ticket.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tickets and only return the `id`
   * const ticketWithIdOnly = await prisma.ticket.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TicketCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TicketCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Ticket.
   * @param {TicketDeleteArgs} args - Arguments to delete one Ticket.
   * @example
   * // Delete one Ticket
   * const Ticket = await prisma.ticket.delete({
   *   where: {
   *     // ... filter to delete one Ticket
   *   }
   * })
   * 
   */
  delete<T extends TicketDeleteArgs>(args: Prisma.SelectSubset<T, TicketDeleteArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Ticket.
   * @param {TicketUpdateArgs} args - Arguments to update one Ticket.
   * @example
   * // Update one Ticket
   * const ticket = await prisma.ticket.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TicketUpdateArgs>(args: Prisma.SelectSubset<T, TicketUpdateArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tickets.
   * @param {TicketDeleteManyArgs} args - Arguments to filter Tickets to delete.
   * @example
   * // Delete a few Tickets
   * const { count } = await prisma.ticket.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TicketDeleteManyArgs>(args?: Prisma.SelectSubset<T, TicketDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tickets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tickets
   * const ticket = await prisma.ticket.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TicketUpdateManyArgs>(args: Prisma.SelectSubset<T, TicketUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tickets and returns the data updated in the database.
   * @param {TicketUpdateManyAndReturnArgs} args - Arguments to update many Tickets.
   * @example
   * // Update many Tickets
   * const ticket = await prisma.ticket.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tickets and only return the `id`
   * const ticketWithIdOnly = await prisma.ticket.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TicketUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TicketUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Ticket.
   * @param {TicketUpsertArgs} args - Arguments to update or create a Ticket.
   * @example
   * // Update or create a Ticket
   * const ticket = await prisma.ticket.upsert({
   *   create: {
   *     // ... data to create a Ticket
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Ticket we want to update
   *   }
   * })
   */
  upsert<T extends TicketUpsertArgs>(args: Prisma.SelectSubset<T, TicketUpsertArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tickets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketCountArgs} args - Arguments to filter Tickets to count.
   * @example
   * // Count the number of Tickets
   * const count = await prisma.ticket.count({
   *   where: {
   *     // ... the filter for the Tickets we want to count
   *   }
   * })
  **/
  count<T extends TicketCountArgs>(
    args?: Prisma.Subset<T, TicketCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TicketCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Ticket.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TicketAggregateArgs>(args: Prisma.Subset<T, TicketAggregateArgs>): Prisma.PrismaPromise<GetTicketAggregateType<T>>

  /**
   * Group by Ticket.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TicketGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TicketGroupByArgs['orderBy'] }
      : { orderBy?: TicketGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TicketGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTicketGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Ticket model
 */
readonly fields: TicketFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Ticket.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TicketClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  cabinet<T extends Prisma.CabinetDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CabinetDefaultArgs<ExtArgs>>): Prisma.Prisma__CabinetClient<runtime.Types.Result.GetResult<Prisma.$CabinetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Ticket model
 */
export interface TicketFieldRefs {
  readonly id: Prisma.FieldRef<"Ticket", 'String'>
  readonly cabinet_id: Prisma.FieldRef<"Ticket", 'String'>
  readonly date_file: Prisma.FieldRef<"Ticket", 'DateTime'>
  readonly numero: Prisma.FieldRef<"Ticket", 'Int'>
  readonly type: Prisma.FieldRef<"Ticket", 'TicketType'>
  readonly etat: Prisma.FieldRef<"Ticket", 'TicketEtat'>
  readonly jeton_public: Prisma.FieldRef<"Ticket", 'String'>
  readonly nom_prive: Prisma.FieldRef<"Ticket", 'String'>
  readonly ordre: Prisma.FieldRef<"Ticket", 'Decimal'>
  readonly grace_expire_le: Prisma.FieldRef<"Ticket", 'DateTime'>
  readonly nb_reintegrations: Prisma.FieldRef<"Ticket", 'Int'>
  readonly cree_le: Prisma.FieldRef<"Ticket", 'DateTime'>
  readonly appele_le: Prisma.FieldRef<"Ticket", 'DateTime'>
  readonly absent_le: Prisma.FieldRef<"Ticket", 'DateTime'>
  readonly debut_consult_le: Prisma.FieldRef<"Ticket", 'DateTime'>
  readonly fin_le: Prisma.FieldRef<"Ticket", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Ticket findUnique
 */
export type TicketFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * Filter, which Ticket to fetch.
   */
  where: Prisma.TicketWhereUniqueInput
}

/**
 * Ticket findUniqueOrThrow
 */
export type TicketFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * Filter, which Ticket to fetch.
   */
  where: Prisma.TicketWhereUniqueInput
}

/**
 * Ticket findFirst
 */
export type TicketFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * Filter, which Ticket to fetch.
   */
  where?: Prisma.TicketWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tickets to fetch.
   */
  orderBy?: Prisma.TicketOrderByWithRelationInput | Prisma.TicketOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tickets.
   */
  cursor?: Prisma.TicketWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tickets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tickets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tickets.
   */
  distinct?: Prisma.TicketScalarFieldEnum | Prisma.TicketScalarFieldEnum[]
}

/**
 * Ticket findFirstOrThrow
 */
export type TicketFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * Filter, which Ticket to fetch.
   */
  where?: Prisma.TicketWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tickets to fetch.
   */
  orderBy?: Prisma.TicketOrderByWithRelationInput | Prisma.TicketOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tickets.
   */
  cursor?: Prisma.TicketWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tickets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tickets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tickets.
   */
  distinct?: Prisma.TicketScalarFieldEnum | Prisma.TicketScalarFieldEnum[]
}

/**
 * Ticket findMany
 */
export type TicketFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * Filter, which Tickets to fetch.
   */
  where?: Prisma.TicketWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tickets to fetch.
   */
  orderBy?: Prisma.TicketOrderByWithRelationInput | Prisma.TicketOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Tickets.
   */
  cursor?: Prisma.TicketWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tickets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tickets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tickets.
   */
  distinct?: Prisma.TicketScalarFieldEnum | Prisma.TicketScalarFieldEnum[]
}

/**
 * Ticket create
 */
export type TicketCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * The data needed to create a Ticket.
   */
  data: Prisma.XOR<Prisma.TicketCreateInput, Prisma.TicketUncheckedCreateInput>
}

/**
 * Ticket createMany
 */
export type TicketCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Tickets.
   */
  data: Prisma.TicketCreateManyInput | Prisma.TicketCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Ticket createManyAndReturn
 */
export type TicketCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * The data used to create many Tickets.
   */
  data: Prisma.TicketCreateManyInput | Prisma.TicketCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Ticket update
 */
export type TicketUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * The data needed to update a Ticket.
   */
  data: Prisma.XOR<Prisma.TicketUpdateInput, Prisma.TicketUncheckedUpdateInput>
  /**
   * Choose, which Ticket to update.
   */
  where: Prisma.TicketWhereUniqueInput
}

/**
 * Ticket updateMany
 */
export type TicketUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Tickets.
   */
  data: Prisma.XOR<Prisma.TicketUpdateManyMutationInput, Prisma.TicketUncheckedUpdateManyInput>
  /**
   * Filter which Tickets to update
   */
  where?: Prisma.TicketWhereInput
  /**
   * Limit how many Tickets to update.
   */
  limit?: number
}

/**
 * Ticket updateManyAndReturn
 */
export type TicketUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * The data used to update Tickets.
   */
  data: Prisma.XOR<Prisma.TicketUpdateManyMutationInput, Prisma.TicketUncheckedUpdateManyInput>
  /**
   * Filter which Tickets to update
   */
  where?: Prisma.TicketWhereInput
  /**
   * Limit how many Tickets to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Ticket upsert
 */
export type TicketUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * The filter to search for the Ticket to update in case it exists.
   */
  where: Prisma.TicketWhereUniqueInput
  /**
   * In case the Ticket found by the `where` argument doesn't exist, create a new Ticket with this data.
   */
  create: Prisma.XOR<Prisma.TicketCreateInput, Prisma.TicketUncheckedCreateInput>
  /**
   * In case the Ticket was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TicketUpdateInput, Prisma.TicketUncheckedUpdateInput>
}

/**
 * Ticket delete
 */
export type TicketDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * Filter which Ticket to delete.
   */
  where: Prisma.TicketWhereUniqueInput
}

/**
 * Ticket deleteMany
 */
export type TicketDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tickets to delete
   */
  where?: Prisma.TicketWhereInput
  /**
   * Limit how many Tickets to delete.
   */
  limit?: number
}

/**
 * Ticket without action
 */
export type TicketDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
}
