
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const TicketType = {
  normal: 'normal',
  urgent: 'urgent',
  acte_court: 'acte_court'
} as const

export type TicketType = (typeof TicketType)[keyof typeof TicketType]


export const TicketEtat = {
  en_attente: 'en_attente',
  appele: 'appele',
  en_consultation: 'en_consultation',
  termine: 'termine',
  absent: 'absent',
  expire: 'expire',
  annule: 'annule'
} as const

export type TicketEtat = (typeof TicketEtat)[keyof typeof TicketEtat]


export const UserRole = {
  nurse: 'nurse',
  admin: 'admin'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]
